export const _ = () => import("https://cdn.jsdelivr.net/npm/lodash/+esm").then((_) => _.default);
export const aq = () => import("https://cdn.jsdelivr.net/npm/arquero/+esm");
export const Arrow = () => import("https://cdn.jsdelivr.net/npm/apache-arrow@17.0.0/+esm");
export const d3 = () => import("https://cdn.jsdelivr.net/npm/d3/+esm");
export const dot = () => import("./dot.js").then((_) => _.dot);
export const duckdb = () => import("https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.0/+esm");
export const DuckDBClient = () => import("./duckdb.js").then((_) => _.DuckDBClient);
export const echarts = () => import("https://cdn.jsdelivr.net/npm/echarts/+esm");
export const htl = () => import("https://cdn.jsdelivr.net/npm/htl/+esm");
export const html = () => import("https://cdn.jsdelivr.net/npm/htl/+esm").then((_) => _.html);
export const svg = () => import("https://cdn.jsdelivr.net/npm/htl/+esm").then((_) => _.svg);
export const Inputs = () => import("./inputs.js");
export const L = () => import("./leaflet.js");
export const mapboxgl = () => import("./mapboxgl.js").then((_) => _.default);
export const md = () => import("./md.js").then((_) => _.md);
export const mermaid = () => import("./mermaid.js").then((_) => _.mermaid);
export const Plot = () => import("https://cdn.jsdelivr.net/npm/@observablehq/plot/+esm");
export const React = () => import("https://cdn.jsdelivr.net/npm/react/+esm");
export const ReactDOM = () => import("https://cdn.jsdelivr.net/npm/react-dom/+esm");
// export const sql = () => import("observablehq:stdlib/duckdb").then((_) => _.sql);
// export const SQLite = () => import("observablehq:stdlib/sqlite").then((_) => _.default);
// export const SQLiteDatabaseClient = () => import("observablehq:stdlib/sqlite").then((_) => _.SQLiteDatabaseClient);
export const tex = () => import("./tex.js").then((_) => _.tex);
export const topojson = () => import("https://cdn.jsdelivr.net/npm/topojson-client/+esm");
// export const vg = () => import("observablehq:stdlib/vgplot").then((_) => _.default());
export const vl = () => import("./vega-lite.js").then((_) => _.vl);
